name: ecobites
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1
environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dots_indicator: ^3.0.0
  flutter:
    sdk: flutter
  google_fonts: ^5.1.0
  image_picker: ^1.1.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_core: ^2.24.2
  shared_preferences: ^2.0.7
  url_launcher: ^6.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets: 
  - assets/logo.png
  - assets/login.png
  - assets/register.png
  - assets/defaultProfilePicture.png
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
