name: ecobites
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1
environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  flutter_chat_ui: ^1.0.5
  google_fonts: ^5.1.0
  iconsax: ^0.0.8
  dots_indicator: ^3.0.0
  get: ^4.6.1
  image_picker: ^1.0.8


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_core: ^2.24.2
  shared_preferences: ^2.0.7
  url_launcher: ^6.0.0
  google_maps_flutter: ^2.2.2
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets: 
  - assets/logo.png
  - assets/login.png
  - assets/register.png
  - assets/defaultProfilePicture.png
  - assets/daurulang.png
  - assets/food.png
  - assets/pupuk.png
  - assets/voucher.png
  - assets/product1.png
  - assets/product2.png
  - assets/product3.png
  - assets/shop.png
  - assets/sosis.jpg
  - assets/kentang.jpg
  - assets/pupukjualan.jpg
  - assets/bahandaur.jpg
  - assets/whatsapp.png
  - assets/instagram.png
  - assets/shop2.png
  - assets/driver.png
  - assets/maps.png
  - assets/shopeepay.png
  - assets/ovo.png
  - assets/master.png
  - assets/linkaja.png
  - assets/gopay.jpg
  - assets/dana.png
  - assets/onboarding1.png
  - assets/onboarding2.png
  - assets/onboarding3.png
  - assets/pupukurea.jpg
  - assets/rotiberjamur.jpg
  - assets/terangbulan.jpg
  - assets/martabak.jpg
  - assets/cahyaa.jpg
  - assets/matahari.jpg
  - assets/mirasa.jpg
  - assets/tokoindonesia.jpg
  - assets/seveneleven.jpg
  - assets/voucher25.png
  - assets/voucher50.png
  - assets/voucherchinese.png
  - assets/voucher45.png
  - assets/mapsContainer.png
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
